### ISSUE TITLE
Сохранять форму обратной связи в БД

### ISSUE THREAD

**Issue by ademaro** [makehtml/flask-bootstrap#3]
```[tasklist]
### Tasks
- [ ] Подключить систему миграций
- [ ] Содать модель
- [ ] Создать миграции
- [ ] Применить миграции
- [ ] Пописать view для сохранения данных (там где отправка в телеграм)
- [ ] Сделать показ заполненных форм для админа
```
